spring:
  rabbit:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    com:
      springframework:
        cloud:
          stream:
            messaging: trace
