spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/planner_todo
    username: postgres
    password: root
  cloud:
#    stream:
#      bindings:
#        todoInputChannel:
#          destination: planner-micro
#          group: planner-group
#      rabbit:
#        bindings:
#          todoInputChannel:
#            consumer:
#              auto-bind-dlq: true
    function:
      definition: newUserActionConsume
    stream:
      bindings:
        newUserActionConsume-in-0.destination: planner-dest
        newUserActionConsume-in-0.group: planner-group
