server:
  port: 0

eureka:
  instance:
    hostname: localhost
    instance-id: eclient:${random.uuid}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

tmpVar: 100

feign:
  circuitbreaker:
    enabled: true
    alphanumeric-ids:
      enabled: true
