#logging:
#  pattern:
#    console: "%C{1.} [%-5level] %d{HH:mm:ss} = %msg%n"

management:
  endpoint:
    gateway:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, beans