spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/planner_users
    username: postgres
    password: root
  cloud:
#    stream:
#      bindings:
#        todoOutputChannel:
#          destination: planner-micro
#          group: planner-group
    function:
      definition: newUserActionProduce
    stream:
      bindings:
        newUserActionProduce-out-0:
          destination: planner-dest
