keycloak:
  auth-server-url: http://localhost:8180/
  resource: user-manage-client
  realm: todoapp-realm
  # ssl не потребуется для внутренних вызовов (локальная разработка)
  ssl-required: external
  credentials:
    secret: 0AyDRSajJckLvUVQBeKBuqWfJEKQZutY
  use-resource-role-mappings: true

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8443/realms/todoapp-realm/protocol/openid-connect/certs
